default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  <<: *default

test:
  <<: *default

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
